"""Constants for Voice Identity integration."""

DOMAIN = "voice_identity"
PLATFORMS: list[str] = []

DATA_CONFIG_MANAGER = "config_manager"
DATA_CAPABILITY_REGISTRY = "capability_registry"
DATA_HEALTH_ENGINE = "health_engine"
DATA_STORAGE_PROVIDER = "storage_provider"
DATA_VOICEPRINT_REGISTRY = "voiceprint_registry"
DATA_VOICEPRINT_LIFECYCLE_MANAGER = "voiceprint_lifecycle_manager"
DATA_VOICEPRINT_REVISION_MANAGER = "voiceprint_revision_manager"
DATA_ARTIFACT_PERSISTENCE_ENGINE = "artifact_persistence_engine"
DATA_ARTIFACT_INTEGRITY_VALIDATOR = "artifact_integrity_validator"
DATA_SAMPLE_VALIDATION_PIPELINE = "sample_validation_pipeline"
DATA_QUALITY_SCORING_ENGINE = "quality_scoring_engine"
DATA_MODEL_EXECUTION_PROVIDER = "model_execution_provider"
DATA_GENERATION_ORCHESTRATOR = "generation_orchestrator"
DATA_GENERATE_VOICEPRINT_OPERATION = "generate_voiceprint_operation"
DATA_GET_VOICEPRINT_STATUS_OPERATION = "get_voiceprint_status_operation"
DATA_GET_CAPABILITIES_OPERATION = "get_capabilities_operation"
DATA_DELETE_SUPERSEDE_VOICEPRINT_OPERATION = "delete_supersede_voiceprint_operation"
DATA_REPAIR_REGISTRY = "repair_registry"
DATA_REPAIR_RESOLVER = "repair_resolver"
DATA_HEALTH_TELEMETRY_PROVIDER = "health_telemetry_provider"
DATA_ATTRIBUTION_FOUNDATION = "attribution_foundation"
DATA_IDENTITY_CONTEXT_GENERATOR = "identity_context_generator"
DATA_CONCIERGE_DISCOVERY_INTEGRATION = "concierge_discovery_integration"
DATA_CONCIERGE_VOICEPROFILE_METADATA_INTEGRATION = "concierge_voiceprofile_metadata_integration"
DATA_STATUS = "status"
DATA_MESSAGE = "message"

CONF_CONFIG_SCHEMA_VERSION = "config_schema_version"
CONF_SERVICE = "service"
CONF_STORAGE = "storage"
CONF_GENERATION = "generation"
CONF_CLEANUP = "cleanup"
CONF_DIAGNOSTICS = "diagnostics"
CONF_FEATURE_FLAGS = "feature_flags"
CONF_ATTRIBUTION = "attribution"

CONF_SERVICE_ENABLED = "enabled"
CONF_STARTUP_TIMEOUT_SECONDS = "startup_timeout_seconds"
CONF_MAX_CACHED_VOICEPRINTS = "max_cached_voiceprints"

CONF_STORAGE_PROVIDER = "provider"
CONF_STORAGE_BASE_PATH = "base_path"
CONF_STORAGE_ENCRYPTION_REQUIRED = "encryption_required"

CONF_MODEL_PREFERENCE = "model_preference"
CONF_MIN_SAMPLE_COUNT = "min_sample_count"
CONF_MAX_SAMPLE_COUNT = "max_sample_count"
CONF_QUALITY_THRESHOLD = "quality_threshold"
CONF_SUPPORTED_MODELS = "supported_models"

CONF_CLEANUP_ENABLED = "enabled"
CONF_SESSION_TIMEOUT_SECONDS = "session_timeout_seconds"
CONF_RECONCILE_ON_STARTUP = "reconcile_on_startup"

CONF_DIAGNOSTICS_ENABLED = "enabled"
CONF_DIAGNOSTICS_ALLOWLIST_ONLY = "allowlist_only"
CONF_INCLUDE_RUNTIME_METRICS = "include_runtime_metrics"

CONF_ENABLE_RUNTIME_ATTRIBUTION = "enable_runtime_attribution"
CONF_ENABLE_REPAIRS = "enable_repairs"
CONF_ENABLE_EXPERIMENTAL_MODELS = "enable_experimental_models"

CONF_DEFAULT_CONFIDENCE_THRESHOLD = "default_confidence_threshold"
CONF_MAX_CANDIDATE_SCOPE_SIZE = "max_candidate_scope_size"
CONF_REQUIRE_ATTRIBUTION_FOR_IDENTITY_CONTEXT = "require_attribution_for_identity_context"

CONFIG_SCHEMA_VERSION_CURRENT = 1
CONFIG_SCHEMA_VERSION_MINIMUM_SUPPORTED = 1

DEFAULT_SERVICE_ENABLED = True
DEFAULT_STARTUP_TIMEOUT_SECONDS = 30
DEFAULT_MAX_CACHED_VOICEPRINTS = 2500

DEFAULT_STORAGE_PROVIDER = "local_filesystem"
DEFAULT_STORAGE_BASE_PATH = "voice_identity"
DEFAULT_STORAGE_ENCRYPTION_REQUIRED = True

DEFAULT_MODEL_PREFERENCE = "ecapa_v1"
DEFAULT_MIN_SAMPLE_COUNT = 6
DEFAULT_MAX_SAMPLE_COUNT = 12
DEFAULT_QUALITY_THRESHOLD = 0.75
DEFAULT_SUPPORTED_MODELS = ("ecapa_v1",)

DEFAULT_CLEANUP_ENABLED = True
DEFAULT_SESSION_TIMEOUT_SECONDS = 900
DEFAULT_RECONCILE_ON_STARTUP = True

DEFAULT_DIAGNOSTICS_ENABLED = True
DEFAULT_DIAGNOSTICS_ALLOWLIST_ONLY = True
DEFAULT_INCLUDE_RUNTIME_METRICS = True

DEFAULT_ENABLE_RUNTIME_ATTRIBUTION = False
DEFAULT_ENABLE_REPAIRS = True
DEFAULT_ENABLE_EXPERIMENTAL_MODELS = False

DEFAULT_DEFAULT_CONFIDENCE_THRESHOLD = 0.7
DEFAULT_MAX_CANDIDATE_SCOPE_SIZE = 25
DEFAULT_REQUIRE_ATTRIBUTION_FOR_IDENTITY_CONTEXT = False
